AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Serverless Forecast Page

Parameters:
  ApplicationName:
    Type: String
    Default: 'ServerlessForecastPage'
  FrontPageApiStageName:
    Type: String
    Default: 'ProdStage'

Resources:
  FrontPageApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: ServerlessForecastPageApi
      EndpointConfiguration: REGIONAL
      StageName: !Ref FrontPageApiStageName
  FileBucket:
    Type: AWS::S3::Bucket
  ForecastIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: forecast.amazonaws.com
          Action: 'sts:AssumeRole'
      Policies:
      - S3CrudPolicy:
          BucketName: !Ref FileBucket
      Policies:
        - PolicyName: ForecastIamRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 's3:*'
                Resource:
                - !Join [ '', [ 'arn:', !Ref 'AWS::Partition', ':s3:::', !Ref FileBucket] ]
                - !Join [ '', [ 'arn:', !Ref 'AWS::Partition', ':s3:::', !Ref FileBucket, '/*'] ]
  FrontPageFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ServerlessForecastPageFrontFunction
      CodeUri: bin/
      Handler: main
      MemorySize: 256
      Runtime: go1.x
      Description: 'Test Front Function'
      Policies:
      Environment:
        Variables:
          REGION: !Ref 'AWS::Region'
          API_PATH: !Join [ '', [ '/', !Ref FrontPageApiStageName, '/api'] ]
      Events:
        FrontPageApi:
          Type: Api
          Properties:
            Path: '/'
            Method: get
            RestApiId: !Ref FrontPageApi
  MainFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ServerlessForecastPageApiFunction
      CodeUri: api/bin/
      Handler: main
      MemorySize: 256
      Runtime: go1.x
      Description: 'Test Forecast Function'
      Policies:
      - S3CrudPolicy:
          BucketName: !Ref FileBucket
      - Statement:
        - Sid: ServerlessForecastPolicy
          Effect: Allow
          Action: 'forecast:*'
          Resource: '*'
        - Sid: ServerlessForecastPassRolePolicy
          Effect: Allow
          Action: 'iam:PassRole'
          Resource: '*'
          Condition:
            StringEquals:
              iam:PassedToService: 'forecast.amazonaws.com'
      Environment:
        Variables:
          REGION: !Ref 'AWS::Region'
          BUCKET_NAME: !Ref 'FileBucket'
          FORECAST_ROLE_ARN: !GetAtt ForecastIamRole.Arn
      Events:
        FrontPageApi:
          Type: Api
          Properties:
            Path: '/api'
            Method: post
            RestApiId: !Ref FrontPageApi

Outputs:
  APIURI:
    Description: "URI"
    Value: !Join [ '', [ 'https://', !Ref FrontPageApi, '.execute-api.',!Ref 'AWS::Region','.amazonaws.com/',!Ref FrontPageApiStageName,'/'] ]
